# Site settings
title: Send Brian Boyko to Coding Bootcamp
email: brian.boyko@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The crowdfunding campaign for Brian to head to coding bootcamp to become a professional coder, fight against institutional corruption, and eventually pay the favor forward to the next generation.   
baseurl: "/crowdfunding/" # the subpath of your site, e.g. /blog/
url: "http://brianboyko.github.io/crowdfunding" # the base hostname & protocol for your site
twitter_username: boyko4tx
github_username:  brianboyko

# Build settings
markdown: kramdown
